"""Generic markdown collection with FTS5 + semantic search."""

from markdown_vault_mcp.collection import Collection
from markdown_vault_mcp.config import CollectionConfig, load_config
from markdown_vault_mcp.exceptions import (
    ConcurrentModificationError,
    ConfigurationError,
    DocumentExistsError,
    DocumentNotFoundError,
    EditConflictError,
    MarkdownMCPError,
    ReadOnlyError,
)
from markdown_vault_mcp.git import GitWriteStrategy, git_write_strategy
from markdown_vault_mcp.types import (
    AttachmentContent,
    AttachmentInfo,
    BacklinkInfo,
    BrokenLinkInfo,
    ChangeSet,
    Chunk,
    CollectionStats,
    CommitDiff,
    DeleteResult,
    EditResult,
    FTSResult,
    HistoryEntry,
    IndexStats,
    LinkInfo,
    MostLinkedNote,
    NoteContent,
    NoteContext,
    NoteInfo,
    OutlinkInfo,
    ParsedNote,
    ReindexResult,
    RenameResult,
    SearchResult,
    SimilarItem,
    WriteCallback,
    WriteResult,
)

__all__ = [
    "AttachmentContent",
    "AttachmentInfo",
    "BacklinkInfo",
    "BrokenLinkInfo",
    "ChangeSet",
    "Chunk",
    "Collection",
    "CollectionConfig",
    "CollectionStats",
    "CommitDiff",
    "ConcurrentModificationError",
    "ConfigurationError",
    "DeleteResult",
    "DocumentExistsError",
    "DocumentNotFoundError",
    "EditConflictError",
    "EditResult",
    "FTSResult",
    "GitWriteStrategy",
    "HistoryEntry",
    "IndexStats",
    "LinkInfo",
    "MarkdownMCPError",
    "MostLinkedNote",
    "NoteContent",
    "NoteContext",
    "NoteInfo",
    "OutlinkInfo",
    "ParsedNote",
    "ReadOnlyError",
    "ReindexResult",
    "RenameResult",
    "SearchResult",
    "SimilarItem",
    "WriteCallback",
    "WriteResult",
    "git_write_strategy",
    "load_config",
]
